spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hefeng1002
    url: jdbc:mysql://127.0.0.1:3306/dbgps
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

